language: node_js
sudo: required
node_js:
  - "8"

services:
  - docker

os:
  - linux

branches:
  only:
    - master

before_install:
  - echo "registry=http://artifact.frank0631.com:4873" > .npmrc
  
script:
  - npm install
  - npm run build
  - docker build -t ratatoskr .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS https://index.docker.io/v1/
  - docker tag ratatoskr $DOCKER_ID_USER/ratatoskr
  - docker push $DOCKER_ID_USER/ratatoskr