language: node_js
sudo: required
node_js:
  - "8"

services:
  - docker

os:
  - linux

branches:
  only:
    - master

script:
  - npm set registry http://artifact.frank0631.com:4873
  - npm install
  - npm run build
  - docker build .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS https://index.docker.io/v1/